"use client";

import { Download } from "lucide-react";

import Button from "@/components/Button";
import { trackEvent } from "@/lib/analytics";
import { SITE } from "@/lib/site";

/**
 * Company profile download.
 *
 * The target is a real, committed file at `/downloads/company-profile.pdf`
 * (generated by `scripts/generate-company-profile-pdf.mjs`), so the button is
 * never a dead end. If the PDF is removed during a later content update, the
 * link must be removed at the same time.
 */
export default function ProfileDownload({
  variant = "secondary",
  size = "lg",
  className = "",
  label = SITE.profileDownload.label,
  icon = true,
}: {
  variant?: "primary" | "secondary" | "quiet" | "onDark" | "accent";
  size?: "md" | "lg";
  className?: string;
  label?: string;
  /** Set false to render the label on its own, without the download glyph. */
  icon?: boolean;
}) {
  return (
    <Button
      href={SITE.profileDownload.href}
      download
      variant={variant}
      size={size}
      className={className}
      onClick={() => trackEvent("profile_downloaded")}
    >
      {icon ? <Download aria-hidden="true" className="h-4 w-4" /> : null}
      {label}
      <span className="sr-only-focusable absolute">
        ({SITE.profileDownload.sizeLabel})
      </span>
    </Button>
  );
}
